### ISSUE TITLE
window.preload = function()

### ISSUE THREAD

**Issue by mchangxe** [avantcontra/p5.we#1]
Hi! Thanks for making this great adapter! One question tho, is it still possible to used the preload function in processing in weapps using this library? I am trying to preload some images to use for later in the app. Thanks again!

**Comment by avantcontra** [comment]
@mchangxe Thks!

The `preload()` function mechanism is normal as p5.js. 

But I found that when `loadImage()` in preload, the image will not be shown after `draw()`. There are two reasons:
1. If `preload()` called, you will need call `canvas.style.visibility = 'visible';` once again in `setup()`, otherwise all the content of the canvas will not be shown.
2. Canvas of the image created by `loadImage()` in `preload()`  is not the same as the canvas in `setup()` or `draw()`. It should be something conflict with WeChat Mini Game. I'll try to find more next. 
For now you can `loadPixels()` in callbackFunction of `loadImage(xxx, callbackFunction)` in `preload()`, and then setup the pixels to another Image created in `draw()`.

**Comment by avantcontra** [comment]
@mchangxe , now you can use preload and loadImage as usual! Thanks @xarray!!
Just pull the latest master branch, and you can find a `loadImage` example in sketch.
